#!/usr/bin/env bash

# Set strict mode if inside a script.
if [ -n "${BASH_SOURCE[0]:-}" ]; then
	set -euo pipefail
fi

EMPTY="foo"

echo "Clearing credentials via 'aws configure set' for default profile"
aws --profile default configure set aws_access_key_id $EMPTY
aws --profile default configure set aws_secret_access_key $EMPTY
aws --profile default configure set aws_session_token $EMPTY
